export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_CAN_GO_BACK = 'UPDATE_CAN_GO_BACK';
export const UPDATE_CAN_GO_FORWARD = 'UPDATE_CAN_GO_FORWARD';

export const TOGGLE_SETTING_DIALOG = 'TOGGLE_SETTING_DIALOG';
export const SET_BEHAVIOR = 'SET_BEHAVIOR';
export const SET_BEHAVIORS = 'SET_BEHAVIORS';
