// System Preferences
export const SET_SYSTEM_PREFERENCE = 'SET_SYSTEM_PREFERENCE';

// Preferences
export const SET_PREFERENCE = 'SET_PREFERENCE';

// Workspaces
export const SET_WORKSPACE = 'SET_WORKSPACE';

// Edit Workspace
export const UPDATE_EDIT_WORKSPACE_FORM = 'UPDATE_EDIT_WORKSPACE_FORM';

// General
export const UPDATE_CAN_GO_BACK = 'UPDATE_CAN_GO_BACK';
export const UPDATE_CAN_GO_FORWARD = 'UPDATE_CAN_GO_FORWARD';
export const UPDATE_DID_FAIL_LOAD = 'UPDATE_DID_FAIL_LOAD';
export const UPDATE_SHOULD_USE_DARK_COLORS = 'UPDATE_SHOULD_USE_DARK_COLORS';
export const UPDATE_THEME_SOURCE = 'UPDATE_THEME_SOURCE';
export const UPDATE_IS_FULL_SCREEN = 'UPDATE_IS_FULL_SCREEN';
export const UPDATE_IS_DEFAULT_MAIL_CLIENT = 'UPDATE_IS_DEFAULT_MAIL_CLIENT';
export const UPDATE_IS_DEFAULT_WEB_BROWSER = 'UPDATE_IS_DEFAULT_WEB_BROWSER';
export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';

// Find In Page
export const CLOSE_FIND_IN_PAGE = 'CLOSE_FIND_IN_PAGE';
export const OPEN_FIND_IN_PAGE = 'OPEN_FIND_IN_PAGE';
export const UPDATE_FIND_IN_PAGE_TEXT = 'UPDATE_FIND_IN_PAGE_TEXT';
export const UPDATE_FIND_IN_PAGE_MATCHES = 'UPDATE_FIND_IN_PAGE_MATCHES';

// Code Injection
export const UPDATE_CODE_INJECTION_FORM = 'UPDATE_CODE_INJECTION_FORM';

// Custom User Agent
export const UPDATE_CUSTOM_USER_AGENT_FORM = 'UPDATE_CUSTOM_USER_AGENT_FORM';

// Auth
export const UPDATE_AUTH_FORM = 'UPDATE_AUTH_FORM';

// About
export const ABOUT_CLOSE = 'ABOUT_CLOSE';
export const ABOUT_OPEN = 'ABOUT_OPEN';

// Notifications
export const UPDATE_PAUSE_NOTIFICATIONS_INFO = 'UPDATE_PAUSE_NOTIFICATIONS_INFO';
