// System Preferences
export const SET_SYSTEM_PREFERENCE = 'SET_SYSTEM_PREFERENCE';

// Preferences
export const SET_PREFERENCE = 'SET_PREFERENCE';

// Workspaces
export const SET_WORKSPACE = 'SET_WORKSPACE';

// Edit Workspace
export const UPDATE_EDIT_WORKSPACE_FORM = 'UPDATE_EDIT_WORKSPACE_FORM';

// General
export const UPDATE_DID_FAIL_LOAD = 'UPDATE_DID_FAIL_LOAD';
export const UPDATE_IS_DARK_MODE = 'UPDATE_IS_DARK_MODE';
export const UPDATE_IS_FULL_SCREEN = 'UPDATE_IS_FULL_SCREEN';
export const UPDATE_IS_DEFAULT_MAIL_CLIENT = 'UPDATE_IS_DEFAULT_MAIL_CLIENT';
export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';

// Find In Page
export const CLOSE_FIND_IN_PAGE = 'CLOSE_FIND_IN_PAGE';
export const OPEN_FIND_IN_PAGE = 'OPEN_FIND_IN_PAGE';
export const UPDATE_FIND_IN_PAGE_TEXT = 'UPDATE_FIND_IN_PAGE_TEXT';
export const UPDATE_FIND_IN_PAGE_MATCHES = 'UPDATE_FIND_IN_PAGE_MATCHES';
