/* findInPage */
export const TOGGLE_FIND_IN_PAGE_DIALOG = 'TOGGLE_FIND_IN_PAGE_DIALOG';
export const UPDATE_FIND_IN_PAGE_TEXT = 'UPDATE_FIND_IN_PAGE_TEXT';
export const UPDATE_FIND_IN_PAGE_MATCHES = 'UPDATE_FIND_IN_PAGE_MATCHES';

/* nav */
export const UPDATE_TARGET_URL = 'UPDATE_TARGET_URL';
export const UPDATE_IS_FAILED = 'UPDATE_IS_FAILED';
export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';
export const UPDATE_CAN_GO_BACK = 'UPDATE_CAN_GO_BACK';
export const UPDATE_CAN_GO_FORWARD = 'UPDATE_CAN_GO_FORWARD';

/* root */
export const ADD_TAB = 'ADD_TAB';
export const REMOVE_TAB = 'REMOVE_TAB';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SWAP_TAB = 'SWAP_TAB';

/* screen */
export const SCREEN_RESIZE = 'SCREEN_RESIZE';

/* settings */
export const TOGGLE_SETTING_DIALOG = 'TOGGLE_SETTING_DIALOG';
