// Auth
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

/* findInPage */
export const TOGGLE_FIND_IN_PAGE_DIALOG = 'TOGGLE_FIND_IN_PAGE_DIALOG';
export const UPDATE_FIND_IN_PAGE_TEXT = 'UPDATE_FIND_IN_PAGE_TEXT';
export const UPDATE_FIND_IN_PAGE_MATCHES = 'UPDATE_FIND_IN_PAGE_MATCHES';

/* nav */
export const UPDATE_TARGET_URL = 'UPDATE_TARGET_URL';
export const UPDATE_IS_FAILED = 'UPDATE_IS_FAILED';
export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';
export const UPDATE_CAN_GO_BACK = 'UPDATE_CAN_GO_BACK';
export const UPDATE_CAN_GO_FORWARD = 'UPDATE_CAN_GO_FORWARD';

/* screen */
export const SCREEN_RESIZE = 'SCREEN_RESIZE';

// Dialogs
// Preferences Dialog
export const DIALOG_PREFERENCES_CLOSE = 'DIALOG_PREFERENCES_CLOSE';
export const DIALOG_PREFERENCES_OPEN = 'DIALOG_PREFERENCES_OPEN';

// Snackbar
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

// User
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAILED = 'USER_GET_FAILED';

// Preferences
export const PREFERENCES_SET = 'PREFERENCES_SET';
