// Auth
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

// Login
export const LOG_IN_FORM_UPDATE = 'LOG_IN_FORM_UPDATE';
export const LOG_IN_SUBMIT_REQUEST = 'LOG_IN_SUBMIT_REQUEST';
export const LOG_IN_SUBMIT_SUCCESS = 'LOG_IN_SUBMIT_SUCCESS';
export const LOG_IN_SUBMIT_FAILED = 'LOG_IN_SUBMIT_FAILED';

// Apps
export const TOP_CHARTS_RESET = 'TOP_CHARTS_RESET';
export const TOP_CHARTS_GET_FAILED = 'TOP_CHARTS_GET_FAILED';
export const TOP_CHARTS_GET_REQUEST = 'TOP_CHARTS_GET_REQUEST';
export const TOP_CHARTS_GET_SUCCESS = 'TOP_CHARTS_GET_SUCCESS';
export const TOP_CHARTS_SET_CATEGORY = 'TOP_CHARTS_SET_CATEGORY';
export const TOP_CHARTS_SET_SORT_BY = 'TOP_CHARTS_SET_SORT_BY';
export const TOP_CHARTS_SET_SORT_ORDER = 'TOP_CHARTS_SET_SORT_ORDER';

// User
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAILED = 'USER_GET_FAILED';

// updater
export const SET_UPDATER_STATUS = 'SET_UPDATER_STATUS';

// Snackbar
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

// Dialogs
// About Dialog
export const DIALOG_ABOUT_CLOSE = 'DIALOG_ABOUT_CLOSE';
export const DIALOG_ABOUT_OPEN = 'DIALOG_ABOUT_OPEN';
// Submit App Dialog
export const DIALOG_SUBMIT_APP_CLOSE = 'DIALOG_SUBMIT_APP_CLOSE';
export const DIALOG_SUBMIT_APP_FORM_UPDATE = 'DIALOG_SUBMIT_APP_FORM_UPDATE';
export const DIALOG_SUBMIT_APP_OPEN = 'DIALOG_SUBMIT_APP_OPEN';
export const DIALOG_SUBMIT_APP_SAVE_REQUEST = 'DIALOG_SUBMIT_APP_SAVE_REQUEST';
export const DIALOG_SUBMIT_APP_SAVE_SUCCESS = 'DIALOG_SUBMIT_APP_SAVE_SUCCESS';

// Route
export const ROUTE_CHANGE = 'ROUTE_CHANGE';

// Search
export const SEARCH_FORM_UPDATE = 'SEARCH_FORM_UPDATE';
export const SEARCH_RESULTS_GET_FAILED = 'SEARCH_SUGGESTIONS_GET_FAILED';
export const SEARCH_RESULTS_GET_REQUEST = 'SEARCH_SUGGESTIONS_GET_REQUEST';
export const SEARCH_RESULTS_GET_SUCCESS = 'SEARCH_SUGGESTIONS_GET_SUCCESS';

// Workspaces Bar
export const WORKSPACES_BAR_SET_ACTIVE = 'WORKSPACES_BAR_SET_ACTIVE';
export const DIALOG_WORKSPACE_CLOSE = 'DIALOG_WORKSPACE_CLOSE';
export const DIALOG_WORKSPACE_OPEN = 'DIALOG_WORKSPACE_OPEN';
export const DIALOG_WORKSPACE_FORM_UPDATE = 'DIALOG_WORKSPACE_FORM_UPDATE';
