export const SCREEN_RESIZE = 'SCREEN_RESIZE';

export const UPDATE_TARGET_URL = 'UPDATE_TARGET_URL';
export const UPDATE_IS_FAILED = 'UPDATE_IS_FAILED';
export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';

export const TOGGLE_SETTING_DIALOG = 'TOGGLE_SETTING_DIALOG';
export const SET_BEHAVIOR = 'SET_BEHAVIOR';

export const TOGGLE_FIND_IN_PAGE_DIALOG = 'TOGGLE_FIND_IN_PAGE_DIALOG';
export const UPDATE_FIND_IN_PAGE_TEXT = 'UPDATE_FIND_IN_PAGE_TEXT';
export const UPDATE_FIND_IN_PAGE_MATCHES = 'UPDATE_FIND_IN_PAGE_MATCHES';

export const ADD_TAB = 'ADD_TAB';
export const CLOSE_TAB = 'CLOSE_TAB';
export const UPDATE_ACTIVE_TAB = 'UPDATE_ACTIVE_TAB';
export const UPDATE_TAB_LAST_URL = 'UPDATE_TAB_LAST_URL';
export const UPDATE_CAN_GO_BACK = 'UPDATE_CAN_GO_BACK';
export const UPDATE_CAN_GO_FORWARD = 'UPDATE_CAN_GO_FORWARD';
