/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
// Route
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

// General
export const UPDATE_FETCHING_LATEST_TEMPLATE_VERSION = 'UPDATE_FETCHING_LATEST_TEMPLATE_VERSION';
export const UPDATE_INSTALLATION_PROGRESS = 'UPDATE_INSTALLATION_PROGRESS';
export const UPDATE_IS_FULL_SCREEN = 'UPDATE_IS_FULL_SCREEN';
export const UPDATE_IS_MAXIMIZED = 'UPDATE_IS_MAXIMIZED';
export const UPDATE_LATEST_TEMPLATE_VERSION = 'UPDATE_LATEST_TEMPLATE_VERSION';
export const UPDATE_MOVING_ALL_APPS = 'UPDATE_MOVING_ALL_APPS';
export const UPDATE_SHOULD_USE_DARK_COLORS = 'UPDATE_SHOULD_USE_DARK_COLORS';

// Preferences
export const SET_PREFERENCE = 'SET_PREFERENCE';
export const SET_PREFERENCES = 'SET_PREFERENCES';

// System Preferences
export const SET_SYSTEM_PREFERENCE = 'SET_SYSTEM_PREFERENCE';

// App Management
export const SET_APP = 'SET_APP';
export const REMOVE_APP = 'REMOVE_APP';
export const CLEAN_APP_MANAGEMENT = 'CLEAN_APP_MANAGEMENT';
export const SET_SCANNING_FOR_INSTALLED = 'SET_SCANNING_FOR_INSTALLED';
export const SORT_APPS = 'SORT_APPS';

// Dialog Create Custom App
export const DIALOG_CREATE_CUSTOM_APP_CLOSE = 'DIALOG_CREATE_CUSTOM_APP_CLOSE';
export const DIALOG_CREATE_CUSTOM_APP_FORM_UPDATE = 'DIALOG_CREATE_CUSTOM_APP_FORM_UPDATE';
export const DIALOG_CREATE_CUSTOM_APP_OPEN = 'DIALOG_CREATE_CUSTOM_APP_OPEN';
export const DIALOG_CREATE_CUSTOM_APP_DOWNLOADING_ICON_UPDATE = 'DIALOG_CREATE_CUSTOM_APP_DOWNLOADING_ICON_UPDATE';

// Dialog Edit App
export const DIALOG_EDIT_APP_CLOSE = 'DIALOG_EDIT_APP_CLOSE';
export const DIALOG_EDIT_APP_FORM_UPDATE = 'DIALOG_EDIT_APP_FORM_UPDATE';
export const DIALOG_EDIT_APP_OPEN = 'DIALOG_EDIT_APP_OPEN';
export const DIALOG_EDIT_APP_DOWNLOADING_ICON_UPDATE = 'DIALOG_EDIT_APP_DOWNLOADING_ICON_UPDATE';

// Dialog License Registration
export const DIALOG_LICENSE_REGISTRATION_CLOSE = 'DIALOG_LICENSE_REGISTRATION_CLOSE';
export const DIALOG_LICENSE_REGISTRATION_FORM_UPDATE = 'DIALOG_LICENSE_REGISTRATION_FORM_UPDATE';
export const DIALOG_LICENSE_REGISTRATION_OPEN = 'DIALOG_LICENSE_REGISTRATION_OPEN';

// Dialog Set Installation Path
export const DIALOG_SET_INSTALLATION_PATH_CLOSE = 'DIALOG_SET_INSTALLATION_PATH_CLOSE';
export const DIALOG_SET_INSTALLATION_PATH_FORM_UPDATE = 'DIALOG_SET_INSTALLATION_PATH_FORM_UPDATE';
export const DIALOG_SET_INSTALLATION_PATH_OPEN = 'DIALOG_SET_INSTALLATION_PATH_OPEN';

// Dialog About
export const DIALOG_ABOUT_OPEN = 'DIALOG_ABOUT_OPEN';
export const DIALOG_ABOUT_CLOSE = 'DIALOG_ABOUT_CLOSE';

// Dialog Open Source Notices
export const DIALOG_OPEN_SOURCE_NOTICES_OPEN = 'DIALOG_OPEN_SOURCE_NOTICES_OPEN';
export const DIALOG_OPEN_SOURCE_NOTICES_CLOSE = 'DIALOG_OPEN_SOURCE_NOTICES_CLOSE';

// Dialog Catalog App Details
export const DIALOG_CATALOG_APP_DETAILS_CLOSE = 'DIALOG_CATALOG_APP_DETAILS_CLOSE';
export const DIALOG_CATALOG_APP_DETAILS_UPDATE_DETAILS = 'DIALOG_CATALOG_APP_DETAILS_UPDATE_DETAILS';
export const DIALOG_CATALOG_APP_DETAILS_OPEN = 'DIALOG_CATALOG_APP_DETAILS_OPEN';

// Dialog Export App Details
export const DIALOG_EXPORT_APP_DETAILS_OPEN = 'DIALOG_EXPORT_APP_DETAILS_OPEN';
export const DIALOG_EXPORT_APP_DETAILS_CLOSE = 'DIALOG_EXPORT_APP_DETAILS_CLOSE';

// Installed
export const INSTALLED_SET_IS_SEARCHING = 'INSTALLED_SET_IS_SEARCHING';
export const INSTALLED_UPDATE_ACTIVE_QUERY = 'INSTALLED_UPDATE_ACTIVE_QUERY';
export const INSTALLED_UPDATE_QUERY = 'INSTALLED_UPDATE_QUERY';
export const INSTALLED_UPDATE_SCROLL_OFFSET = 'INSTALLED_UPDATE_SCROLL_OFFSET';
export const INSTALLED_UPDATE_SORTED_APP_IDS = 'INSTALLED_UPDATE_SORTED_APP_IDS';

// Updater
export const UPDATE_UPDATER = 'UPDATE_UPDATER';

// User
export const SET_USER_STATE = 'SET_USER_STATE';
export const SET_PUBLIC_PROFILE = 'SET_PUBLIC_PROFILE';
export const CLEAR_USER_STATE = 'CLEAR_USER_STATE';
