// Local
export const LOCAL_SET_APP = 'LOCAL_SET_APP';
export const LOCAL_REMOVE_APP = 'LOCAL_REMOVE_APP';

// Apps
export const POPULAR_APPS_RESET = 'POPULAR_APPS_RESET';
export const POPULAR_APPS_GET_FAILED = 'POPULAR_APPS_GET_FAILED';
export const POPULAR_APPS_GET_REQUEST = 'POPULAR_APPS_GET_REQUEST';
export const POPULAR_APPS_GET_SUCCESS = 'POPULAR_APPS_GET_SUCCESS';

// updater
export const SET_UPDATER_STATUS = 'SET_UPDATER_STATUS';

// Snackbar
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

// About Dialog
export const DIALOG_ABOUT_CLOSE = 'DIALOG_ABOUT_CLOSE';
export const DIALOG_ABOUT_OPEN = 'DIALOG_ABOUT_OPEN';
// Confirm Uninstall App Dialog
export const DIALOG_CONFIRM_UNINSTALL_APP_CLOSE = 'DIALOG_CONFIRM_UNINSTALL_APP_CLOSE';
export const DIALOG_CONFIRM_UNINSTALL_APP_OPEN = 'DIALOG_CONFIRM_UNINSTALL_APP_OPEN';
export const DIALOG_CONFIRM_UNINSTALL_APP_SAVE_REQUEST = 'DIALOG_CONFIRM_UNINSTALL_APP_SAVE_REQUEST';
export const DIALOG_CONFIRM_UNINSTALL_APP_SAVE_SUCCESS = 'DIALOG_CONFIRM_UNINSTALL_APP_SAVE_SUCCESS';

// Route
export const ROUTE_CHANGE = 'ROUTE_CHANGE';

// Update WebCatalog first
export const DIALOG_UPDATE_WEBCATALOG_FIRST_CLOSE = 'DIALOG_UPDATE_WEBCATALOG_FIRST_CLOSE';
export const DIALOG_UPDATE_WEBCATALOG_FIRST_OPEN = 'DIALOG_UPDATE_WEBCATALOG_FIRST_OPEN';

// Version
export const VERSION_GET_REQUEST = 'VERSION_GET_REQUEST';
export const VERSION_GET_SUCCESS = 'VERSION_GET_SUCCESS';
export const VERSION_GET_FAILED = 'VERSION_GET_FAILED';
