// Apps
export const HOME_GET_FAILED = 'HOME_GET_FAILED';
export const HOME_GET_REQUEST = 'HOME_GET_REQUEST';
export const HOME_GET_SUCCESS = 'HOME_GET_SUCCESS';
export const HOME_RESET = 'HOME_RESET';
export const HOME_UPDATE_CURRENT_QUERY = 'HOME_UPDATE_CURRENT_QUERY';
export const HOME_UPDATE_QUERY = 'HOME_UPDATE_QUERY';

// Route
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

// General
export const UPDATE_SHOULD_USE_DARK_COLORS = 'UPDATE_SHOULD_USE_DARK_COLORS';
export const UPDATE_THEME_SOURCE = 'UPDATE_THEME_SOURCE';
export const UPDATE_IS_FULL_SCREEN = 'UPDATE_IS_FULL_SCREEN';
export const UPDATE_FETCHING_LATEST_TEMPLATE_VERSION = 'UPDATE_FETCHING_LATEST_TEMPLATE_VERSION';
export const UPDATE_LATEST_TEMPLATE_VERSION = 'UPDATE_LATEST_TEMPLATE_VERSION';
export const UPDATE_MOVING_ALL_APPS = 'UPDATE_MOVING_ALL_APPS';

// Preferences
export const SET_PREFERENCE = 'SET_PREFERENCE';

// System Preferences
export const SET_SYSTEM_PREFERENCE = 'SET_SYSTEM_PREFERENCE';

// App Management
export const SET_APP = 'SET_APP';
export const REMOVE_APP = 'REMOVE_APP';
export const CLEAN_APP_MANAGEMENT = 'CLEAN_APP_MANAGEMENT';

// Dialog Create Custom App
export const DIALOG_CREATE_CUSTOM_APP_CLOSE = 'DIALOG_CREATE_CUSTOM_APP_CLOSE';
export const DIALOG_CREATE_CUSTOM_APP_FORM_UPDATE = 'DIALOG_CREATE_CUSTOM_APP_FORM_UPDATE';
export const DIALOG_CREATE_CUSTOM_APP_OPEN = 'DIALOG_CREATE_CUSTOM_APP_OPEN';

// Dialog License Registration
export const DIALOG_LICENSE_REGISTRATION_CLOSE = 'DIALOG_LICENSE_REGISTRATION_CLOSE';
export const DIALOG_LICENSE_REGISTRATION_FORM_UPDATE = 'DIALOG_LICENSE_REGISTRATION_FORM_UPDATE';
export const DIALOG_LICENSE_REGISTRATION_OPEN = 'DIALOG_LICENSE_REGISTRATION_OPEN';

// Dialog Set Installation Path
export const DIALOG_SET_INSTALLATION_PATH_CLOSE = 'DIALOG_SET_INSTALLATION_PATH_CLOSE';
export const DIALOG_SET_INSTALLATION_PATH_FORM_UPDATE = 'DIALOG_SET_INSTALLATION_PATH_FORM_UPDATE';
export const DIALOG_SET_INSTALLATION_PATH_OPEN = 'DIALOG_SET_INSTALLATION_PATH_OPEN';

// Dialog About
export const DIALOG_ABOUT_OPEN = 'DIALOG_ABOUT_OPEN';
export const DIALOG_ABOUT_CLOSE = 'DIALOG_ABOUT_CLOSE';

// Dialog Choose Engine
export const DIALOG_CHOOSE_ENGINE_CLOSE = 'DIALOG_CHOOSE_ENGINE_CLOSE';
export const DIALOG_CHOOSE_ENGINE_FORM_UPDATE = 'DIALOG_CHOOSE_ENGINE_FORM_UPDATE';
export const DIALOG_CHOOSE_ENGINE_OPEN = 'DIALOG_CHOOSE_ENGINE_OPEN';

// Dialog Choose Engine Preference
export const DIALOG_SET_PREFERRED_ENGINE_CLOSE = 'DIALOG_SET_PREFERRED_ENGINE_CLOSE';
export const DIALOG_SET_PREFERRED_ENGINE_FORM_UPDATE = 'DIALOG_SET_PREFERRED_ENGINE_FORM_UPDATE';
export const DIALOG_SET_PREFERRED_ENGINE_OPEN = 'DIALOG_SET_PREFERRED_ENGINE_OPEN';

// Installed
export const INSTALLED_UPDATE_QUERY = 'INSTALLED_UPDATE_QUERY';

// Updater
export const UPDATE_UPDATER = 'UPDATE_UPDATER';
