// Local
export const LOCAL_SET_APP = 'LOCAL_SET_APP';
export const LOCAL_REMOVE_APP = 'LOCAL_REMOVE_APP';

// Apps
export const DIRECTORY_GET_FAILED = 'DIRECTORY_GET_FAILED';
export const DIRECTORY_GET_REQUEST = 'DIRECTORY_GET_REQUEST';
export const DIRECTORY_GET_SUCCESS = 'DIRECTORY_GET_SUCCESS';
export const DIRECTORY_RESET = 'DIRECTORY_RESET';
export const DIRECTORY_UPDATE_CURRENT_QUERY = 'DIRECTORY_UPDATE_CURRENT_QUERY';
export const DIRECTORY_UPDATE_QUERY = 'DIRECTORY_UPDATE_QUERY';

// updater
export const SET_UPDATER_STATUS = 'SET_UPDATER_STATUS';

// Snackbar
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

// About Dialog
export const DIALOG_ABOUT_CLOSE = 'DIALOG_ABOUT_CLOSE';
export const DIALOG_ABOUT_OPEN = 'DIALOG_ABOUT_OPEN';
// Confirm Uninstall App Dialog
export const DIALOG_CONFIRM_UNINSTALL_APP_CLOSE = 'DIALOG_CONFIRM_UNINSTALL_APP_CLOSE';
export const DIALOG_CONFIRM_UNINSTALL_APP_OPEN = 'DIALOG_CONFIRM_UNINSTALL_APP_OPEN';
export const DIALOG_CONFIRM_UNINSTALL_APP_SAVE_REQUEST = 'DIALOG_CONFIRM_UNINSTALL_APP_SAVE_REQUEST';
export const DIALOG_CONFIRM_UNINSTALL_APP_SAVE_SUCCESS = 'DIALOG_CONFIRM_UNINSTALL_APP_SAVE_SUCCESS';

// Route
export const ROUTE_CHANGE = 'ROUTE_CHANGE';

// Update Appifier first
export const DIALOG_UPDATE_WEBCATALOG_FIRST_CLOSE = 'DIALOG_UPDATE_WEBCATALOG_FIRST_CLOSE';
export const DIALOG_UPDATE_WEBCATALOG_FIRST_OPEN = 'DIALOG_UPDATE_WEBCATALOG_FIRST_OPEN';

// Version
export const VERSION_GET_REQUEST = 'VERSION_GET_REQUEST';
export const VERSION_GET_SUCCESS = 'VERSION_GET_SUCCESS';
export const VERSION_GET_FAILED = 'VERSION_GET_FAILED';

// Create Custom Apps
export const DIALOG_CREATE_CUSTOM_APP_CLOSE = 'DIALOG_CREATE_CUSTOM_APP_CLOSE';
export const DIALOG_CREATE_CUSTOM_APP_OPEN = 'DIALOG_CREATE_CUSTOM_APP_OPEN';
export const DIALOG_CREATE_CUSTOM_APP_FORM_UPDATE = 'DIALOG_CREATE_CUSTOM_APP_FORM_UPDATE';
export const DIALOG_CREATE_CUSTOM_APP_CREATE_FAILED = 'DIALOG_CREATE_CUSTOM_APP_CREATE_FAILED';
export const DIALOG_CREATE_CUSTOM_APP_CREATE_REQUEST = 'DIALOG_CREATE_CUSTOM_APP_CREATE_REQUEST';
export const DIALOG_CREATE_CUSTOM_APP_CREATE_SUCCESS = 'DIALOG_CREATE_CUSTOM_APP_CREATE_SUCCESS';

// Dialogs
// Preferences Dialog
export const DIALOG_PREFERENCES_CLOSE = 'DIALOG_PREFERENCES_CLOSE';
export const DIALOG_PREFERENCES_OPEN = 'DIALOG_PREFERENCES_OPEN';

// Preferences
export const PREFERENCES_SET = 'PREFERENCES_SET';
