// Auth
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

// Login
export const LOG_IN_FORM_UPDATE = 'LOG_IN_FORM_UPDATE';
export const LOG_IN_SUBMIT_REQUEST = 'LOG_IN_SUBMIT_REQUEST';
export const LOG_IN_SUBMIT_SUCCESS = 'LOG_IN_SUBMIT_SUCCESS';
export const LOG_IN_SUBMIT_FAILED = 'LOG_IN_SUBMIT_FAILED';

// User
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAILED = 'USER_GET_FAILED';

// Snackbar
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

// Dialogs
// Account Dialogs
export const DIALOG_ACCOUNT_PASSWORD_CLOSE = 'DIALOG_ACCOUNT_CLOSE';
export const DIALOG_ACCOUNT_PASSWORD_FORM_UPDATE = 'DIALOG_ACCOUNT_PASSWORD_FORM_UPDATE';
export const DIALOG_ACCOUNT_PASSWORD_OPEN = 'DIALOG_ACCOUNT_OPEN';
export const DIALOG_ACCOUNT_PASSWORD_SAVE_REQUEST = 'DIALOG_ACCOUNT_PASSWORD_SAVE_REQUEST';
export const DIALOG_ACCOUNT_PASSWORD_SAVE_SUCCESS = 'DIALOG_ACCOUNT_PASSWORD_SAVE_SUCCESS';
export const DIALOG_ACCOUNT_PROFILE_CLOSE = 'DIALOG_ACCOUNT_PROFILE_CLOSE';
export const DIALOG_ACCOUNT_PROFILE_FORM_UPDATE = 'DIALOG_ACCOUNT_PROFILE_FORM_UPDATE';
export const DIALOG_ACCOUNT_PROFILE_OPEN = 'DIALOG_ACCOUNT_PROFILE_OPEN';
export const DIALOG_ACCOUNT_PROFILE_SAVE_REQUEST = 'DIALOG_ACCOUNT_PROFILE_SAVE_REQUEST';
export const DIALOG_ACCOUNT_PROFILE_SAVE_SUCCESS = 'DIALOG_ACCOUNT_PROFILE_SAVE_SUCCESS';
export const DIALOG_ACCOUNT_SECTION_CHANGE = 'DIALOG_ACCOUNT_SECTION_CHANGE';
