export const SCREEN_RESIZE = 'SCREEN_RESIZE';

export const SET_STATUS = 'SET_STATUS';
export const ADD_APPS = 'ADD_APPS';
export const RESET_HOME = 'RESET_HOME';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SEARCH_HITS = 'SET_SEARCH_HITS';
export const SET_SEARCH_STATUS = 'SET_SEARCH_STATUS';

export const TOGGLE_CUSTOM_DIALOG = 'TOGGLE_CUSTOM_DIALOG';
export const SET_CUSTOM_VALUE = 'SET_CUSTOM_VALUE';
export const SET_CUSTOM_STATUS = 'SET_CUSTOM_STATUS';

export const SET_MANAGED_APP = 'SET_MANAGED_APP';
export const REMOVE_MANAGED_APP = 'REMOVE_MANAGED_APP';
